# Generated by Django 5.1.5 on 2025-02-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='style',
            field=models.CharField(choices=[('noidea', '잘 모르겠어요'), ('casual', '캐주얼'), ('formal', '포멀'), ('sporty', '스포티'), ('street', '스트릿')], default='noidea', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
