# Generated by Django 5.1.5 on 2025-02-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile_default.svg', null=True, upload_to='profile_images/'),
        ),
    ]
