# Generated by Django 5.1.5 on 2025-02-01 06:10

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_admin",
            new_name="is_staff",
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                default=user.models.generate_temp_nickname, max_length=30, unique=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casual", "캐주얼"),
                    ("formal", "포멀"),
                    ("sporty", "스포티"),
                    ("street", "스트릿"),
                ],
                max_length=20,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(20)],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_50", "50kg 미만"),
                    ("50_60", "50kg ~ 60kg"),
                    ("60_70", "60kg ~ 70kg"),
                    ("over_70", "70kg 이상"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
