# Generated by Django 5.1.5 on 2025-01-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_age_customuser_gender_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='style',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
