# Generated by Django 5.1.5 on 2025-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=30),
        ),
    ]
