# Generated by Django 5.1.5 on 2025-01-30 11:23

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=user.models.generate_temp_nickname, max_length=30, unique=True),
        ),
    ]
