# Generated by Django 5.1.5 on 2025-02-01 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='style',
            field=models.CharField(blank=True, choices=[('casual', '캐주얼'), ('formal', '포멀'), ('sporty', '스포티'), ('street', '스트릿')], max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
